# Generated by Django 3.2.1 on 2021-05-22 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_semester_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='FGParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_participated_events', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'fg_participations',
            },
        ),
        migrations.CreateModel(
            name='FocusGroupManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FocusGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_events', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
                ('leaders', models.ManyToManyField(related_name='leading_focus_groups', to='core.UserProfile')),
                ('members', models.ManyToManyField(related_name='joined_focus_groups', through='focusgroup.FGParticipation', to='core.UserProfile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_groups', to='core.semester')),
            ],
            options={
                'db_table': 'focus_groups',
            },
        ),
        migrations.AddField(
            model_name='fgparticipation',
            name='focus_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focusgroup.focusgroup'),
        ),
        migrations.AddField(
            model_name='fgparticipation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.CreateModel(
            name='FGEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('focus_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focusgroup.focusgroup')),
                ('participants', models.ManyToManyField(blank=True, to='core.UserProfile')),
            ],
            options={
                'db_table': 'fg_event',
            },
        ),
    ]
