# Generated by Django 3.2.1 on 2021-05-19 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_semester_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('gm', 'general meeting'), ('social', 'social')], max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('code', models.UUIDField(default=uuid.uuid5, editable=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='core.userprofile')),
                ('participants', models.ManyToManyField(to='core.UserProfile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.semester')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
