# Generated by Django 3.2.1 on 2021-05-22 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
