# Generated by Django 3.2.1 on 2021-05-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210516_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='term',
            field=models.CharField(choices=[('spr', 'spring'), ('fal', 'fall')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('ALU', 'Alumni'), ('WAI', 'Waiting'), ('SUS', 'Suspended'), ('BAN', 'Banned')], default='WAI', max_length=3),
        ),
    ]
