# Generated by Django 3.2.1 on 2021-10-31 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211030_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Korea', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Seongmin Choo', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MAL', 'Male'), ('FEM', 'Female')], default='MAL', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='majors',
            field=models.ManyToManyField(related_name='user_major', to='core.Major'),
        ),
        migrations.AddField(
            model_name='user',
            name='minors',
            field=models.ManyToManyField(related_name='user_minor', to='core.Major'),
        ),
        migrations.AlterField(
            model_name='major',
            name='major',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
